/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIDORLOCAL_H_RPCGEN
#define _SERVIDORLOCAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct nombreContenido {
	char *contenido;
	char *nombre;
};
typedef struct nombreContenido nombreContenido;

struct nombreVersion {
	int v;
	char *nombre;
};
typedef struct nombreVersion nombreVersion;

#define ej2 0x20000001
#define ej2v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define crearArchivo 1
extern  int * creararchivo_1(char **, CLIENT *);
extern  int * creararchivo_1_svc(char **, struct svc_req *);
#define modificarArchivo 2
extern  int * modificararchivo_1(nombreContenido *, CLIENT *);
extern  int * modificararchivo_1_svc(nombreContenido *, struct svc_req *);
#define tamanoArchivo 3
extern  long * tamanoarchivo_1(char **, CLIENT *);
extern  long * tamanoarchivo_1_svc(char **, struct svc_req *);
#define getArchivo 4
extern  char ** getarchivo_1(nombreVersion *, CLIENT *);
extern  char ** getarchivo_1_svc(nombreVersion *, struct svc_req *);
#define listarArchivos 5
extern  char ** listararchivos_1(void *, CLIENT *);
extern  char ** listararchivos_1_svc(void *, struct svc_req *);
extern int ej2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define crearArchivo 1
extern  int * creararchivo_1();
extern  int * creararchivo_1_svc();
#define modificarArchivo 2
extern  int * modificararchivo_1();
extern  int * modificararchivo_1_svc();
#define tamanoArchivo 3
extern  long * tamanoarchivo_1();
extern  long * tamanoarchivo_1_svc();
#define getArchivo 4
extern  char ** getarchivo_1();
extern  char ** getarchivo_1_svc();
#define listarArchivos 5
extern  char ** listararchivos_1();
extern  char ** listararchivos_1_svc();
extern int ej2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nombreContenido (XDR *, nombreContenido*);
extern  bool_t xdr_nombreVersion (XDR *, nombreVersion*);

#else /* K&R C */
extern bool_t xdr_nombreContenido ();
extern bool_t xdr_nombreVersion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIDORLOCAL_H_RPCGEN */
