/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ServidorLocal.h"

bool_t
xdr_nombreContenido (XDR *xdrs, nombreContenido *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->contenido, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nombreVersion (XDR *xdrs, nombreVersion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->v))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	return TRUE;
}
