/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ej2.h"

bool_t
xdr_nombreContenido (XDR *xdrs, nombreContenido *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->contenido, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nombre, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nombreVersion (XDR *xdrs, nombreVersion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->v))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nombre, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
