/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "binder.h"


void
binder_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char * registrarse_1_arg;
	char * *result_2;
	char *getipregistradas_1_arg;
	void  *result_3;
	char * eliminarip_1_arg;
	char * *result_4;
	char *update_1_arg;
	int  *result_5;
	char * getversionaescribir_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, binder, binderv1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarse_1(&registrarse_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = getipregistradas_1((void*)&getipregistradas_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = eliminarip_1(&eliminarip_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = update_1((void*)&update_1_arg, clnt);
	if (result_4 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = getversionaescribir_1(&getversionaescribir_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	re
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	binder_1 (host);
exit (0);
}
