/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "binder.h"
#include <string.h>
//Contiene el nombre del archivo y la última version del mismo

//Contiene ips activas
char* ips[6];
int cantidadElementos=0;

//Tabla de archivos con la ultima version
archivoVersion arch[500];
int cantArch=0;

void *
registrarse_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	if (cantidadElementos<6)
	{
	  ips[cantidadElementos]=*argp;
	  cantidadElementos++;
	}

	return (void *) &result;
}

char **
getipregistradas_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	result=(char *)malloc(96);
	result=ips;

	return &result;
}

void *
eliminarip_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	int i,j;
	int encontre;
	i=0;
	encontre=0;
	while (i<cantidadElementos && !encontre)
	{
	  if (!strcmp(ips[i],*argp))
	  {
	    encontre=1;
	    ips[i]=0;
	    cantidadElementos--;
	  }
	  else
	  {
	    i++;
	  }
	}
	for (j=i;j<5;j++)
	{
	  ips[j]=ips[j+1];
	}

	return (void *) &result;
}

char **
update_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	result=(char * )malloc(500* sizeof(archivoVersion));
	result=arch;

	return &result;
}

int *
getversionaescribir_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
	int encontre;
	i=0;
	encontre=0;
	while (i<cantArch && !encontre)
	{
	  if (!strcmp(arch[i].archivo,*argp))
	  {
	    encontre=1;
	    (arch[i].v)++;
	    result=arch[i].v;
	  }
	  i++;
	}
	if (encontre==0)
	{
	  result=0;
	  arch[cantArch].archivo=*argp;
	  arch[cantArch].v=0;
	  cantArch++;
	}
	return &result;
}
