/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "binder.h"

bool_t
xdr_archivoVersion (XDR *xdrs, archivoVersion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->v))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->archivo, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
